name: Lint and Validate Scripts & JSON

on:
  push:
    paths:
      - '**/*.sh'
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.json'

jobs:
  lint:
    name: Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix jq shellcheck

      - name: Normalize line endings in shell scripts
        run: |
          find . -name '*.sh' -exec dos2unix {} +

      - name: Lint shell scripts with shellcheck
        run: |
          find . -name '*.sh' -print0 | xargs -0 -P"$(nproc)" -I{} shellcheck "{}"

      - name: Check shell scripts for syntax errors
        run: |
          find . -name '*.sh' -print0 | xargs -0 -P"$(nproc)" -I{} bash -n "{}"

      - name: Validate JSON files with jq
        run: |
          find . -name '*.json' -print0 | xargs -0 -P"$(nproc)" -I{} jq empty "{}"
